### ISSUE TITLE
Where to get full code on components part ?

### ISSUE THREAD

**Issue by dleurs** [chayanforyou/flutter_material_3_demo#2]
Thank you very much for your incredible work !

A question : where is the full code for components ?

When cloning the repo : 

![image](https://github.com/chayanforyou/flutter_material_3_demo/assets/58068925/a25a207f-2884-40ed-a94d-3fbd662d2fe2)

Inside https://flutter.github.io/samples/web/material_3_demo/#/ there are more components

![image](https://github.com/chayanforyou/flutter_material_3_demo/assets/58068925/c8f2d0c9-9326-44d1-855e-59bb2b44bf9c)

Thank you very much !

**Comment by dleurs** [comment]
Here https://github.com/flutter/samples/blob/main/material_3_demo/lib/component_screen.dart

**Comment by chayanforyou** [comment]
Now check it out I have updated with new components.

Thanks
